### ISSUE TITLE
TUI mode: tinylog background highlighted for no reason

### ISSUE THREAD

**Issue by UncleReaton** [bacardi55/gtl#8]
## Only in TUI mode: 
After the latest mention (in time therefore the first to appear in the feed) every single tinylog has a highlighted background (without bold font unlike intended Highlights)

![](https://lutim.lagout.org/BuORcQpT/kyH8WOpK)
As it's visible on the pic, the tinylog before @\szczezuja's tinylog from 13/06 has the normal behavior (no highlighted background) but those following haven't.

**Comment by bacardi55** [comment]
Hm, weird as I don't have this on my terminal but it seems it's a background color issue (we see the same in the menu box at the top that shouldn't have this grey background… 
Funny everything is fully black on mine but I'll fix this soon, sorry about this.

**Comment by UncleReaton** [comment]
Well, I tried on 2 others terminal emulators and it seems to be a terminal issue more than a gtl one... I'll test on another computer.

![](https://lutim.lagout.org/oeHKeL0N/eOOPu1F0)
(From left to right: urxvt-term, xfce term, simple term)

**Comment by UncleReaton** [comment]
### My previous tests were on Manjaro 21.0.6 using urxvt-term, xfce4-term, simple term.

## I just tested on Xubuntu 20.04.2 LTS and here are the results:
![](https://lutim.lagout.org/3WiCvb23/i9GSJokr)
- top left corner: urxvt-term [1]
- top right corner: xfce4-term [2]
- bottom left corner: terminator [3]
- bottom right corner: alacritty [4]

As you can see the problem is present in [1], [2] and [4]. Only [3] is behaving as expected. However on my previous tests [2] was the one behaving correctly.

xfce4-terminal's versions:
- 0.8.10 on Manjaro (in my previous message)
- 0.8.9.1 on Ubuntu => the last version for ubuntu 20.04 LTS (this message)

**Comment by bacardi55** [comment]
Thanks a lot for the great tests.
I've done some additional test too with terminator, urxvt and xterm.
On "clean urxvt", I have a white background, and it makes gtl break because the "return to default background make it white instead of black.
![latest-screenshot](https://user-images.githubusercontent.com/311143/122064516-80ffeb00-cdf1-11eb-97ab-a232958816df.png)

If I add my .XDefault with a background color, then it works as expected:
![latest-screenshot](https://user-images.githubusercontent.com/311143/122064683-9d9c2300-cdf1-11eb-9e70-77802dbb4528.png)

On xterm (no specific config, has a black background by default): it works fine.

So my understanding/guess here is that the bug happen when you have a dedicated background color setup for your term emulator… So the easiest thing would be to enforce black background as the app is blacked by default.

**Comment by bacardi55** [comment]
I'm wondering if that will break urxvt and then i'll have to impose the background color (or make it configurable, but i don't want to enter the complexity of "custom theme" for gtl…)

**Comment by UncleReaton** [comment]
I've changed my background color in xfce (the one where it was fine) to an horrible color and yes it's showing the term background instead. Yeah I think that imposing a black background is a good idea. There is no need to go with custom color scheme IMO.

**Comment by bacardi55** [comment]
i'll look at it tonight, but I may be able to impose from the start the defined background color, and this not see the difference between before and after. If I can't, it will be black background for all :p

**Comment by bacardi55** [comment]
I've pushed a quick fix in master to force black background for now as I don't think I'll work a lot on gtl tonight (at least on this one).
Let me know if you can test it :)

**Comment by UncleReaton** [comment]
Everything works fine except for the menu box which still has the issue. :)

**Comment by bacardi55** [comment]
Thanks, should be good now…

**Comment by UncleReaton** [comment]
And... that's a wrap!

It's all gone :D.

**Comment by UncleReaton** [comment]
Fixed in f69bdb471dfe3042e16863dce7ca4fa1653cb8fc . 🎉
